#! /bin/bash

set -e

DECODE=$1
shift

PATH=.:$PATH

_decode() {
    ${CHECKER} ${DECODE} --type emu --definitions "$@"
}

for i; do
    : $i
    case $i in
      *regstream-*.bin)
	    _decode $i > /dev/null
	    ;;
    esac

    case $i in
      *regstream-ar0144.bin)
	    _decode $i --value 0xffff 0x301a
	    ;;

      *regstream-tw99x0.bin)
	    _decode $i --value 0x23   0x01
	    ;;
    esac
done
