variables:
  X_CI_LIBURI: "https://github.com/sigma-embedded/elito-decode-registers.git"
  X_CI_INSTDIR: "${CI_PROJECT_DIR}/../inst"

before_script:
  - rm -rf ../decode-lib ${X_CI_INSTDIR}
  - |
    if test x"${CI_BUILD_TRIGGERED}" = xtrue; then
      git clone "${X_CI_UPSTREAM_URI}" ../decode-lib
      git -C ../decode-lib reset --no-quiet --hard "${X_CI_UPSTREAM_REF}"
    else
      git clone "${X_CI_LIBURI}" ../decode-lib
    fi

    git -C ../decode-lib branch -av
  - prefix=${X_CI_INSTDIR}
  - export prefix
  - make -e -C ../decode-lib install
  - PATH=${X_CI_INSTDIR}/bin:$PATH

  - |
    _make() {
        set -x
        make -j -e "$@" all
        make -j -e "$@" install DESTDIR='tmp-inst'
        make -j -e "$@" clean
        set +x
    }

build:direct:
  script:
    - _make

build:vpath:
  script:
    - mkdir -p build
    - _make -C build -f ../Makefile
